### ISSUE TITLE
s3 files 404

### ISSUE THREAD

**Issue by fabiotatsuo** [kali/dazone#1]
Hi, I was reading your blog, found it interesting and come here to try running local but I am getting error 404 on s3 files... did they moved? I know it has been few years.

Thanks

**Comment by kali** [comment]
Hey ! Glad you found it interesting.

I just gave it a try, and I actually can fetch the files. (Note that I do not own the bucket where they come from.) The following did work.

```
SET=tiny                                                                                                                                                                                                                           TABLE=uservisits
mkdir -p data/text-deflate/$SET/$TABLE
s3cmd get --recursive s3://big-data-benchmark/pavlo/text-deflate/$SET/$TABLE/ data/text-deflate/$SET/$TABLE
```

You need to setup s3cmd (or something equivalent) and you actually need an aws account (or IAM with with read access on s3) to be able to read from the big-data-benchmark bucket.

**Comment by kali** [comment]
Tell me if I can help you more

**Comment by fabiotatsuo** [comment]
Very interesting, I read it full yesterday. Still I am going to read more times to get better.

Sorry about the 404 mistake, I check again and I could get both tiny and 5nodes. It is there.

I remember double checking the address... and also tried to ls the bucket. I am using aws cli since I had installed.

Thanks again
